format = """
[](#2B3339)\
$python$username\
[](bg:#323C41 fg:#2B3339)\
$directory\
[](fg:#323C41 bg:#3A454A)\
$git_branch$git_status\
[](fg:#3A454A bg:#83C092)\
$time\
[ ](fg:#83C092)\
"""
command_timeout = 1200
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
# User: Everforest Dark Hard BG (#2B3339), Foreground (#D3C6AA)
style_user = "bg:#2B3339 fg:#D3C6AA"
# Root: Everforest Orange (#E69875), Dark Hard FG (#2B3339)
style_root = "bg:#E69875 fg:#2B3339"
format = '[ $user ]($style)'

[directory]
# Directory: Everforest Dark Medium BG (#323C41), Foreground (#D3C6AA)
style = "bg:#323C41 fg:#D3C6AA"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

 

 

 

 

[git_branch]
symbol = ""
# Git Branch: Everforest Dark Soft BG (#3A454A), Yellow (#DBBC7F)
style = "bg:#3A454A fg:#DBBC7F"
format = '[ $symbol $branch ]($style)'

[git_status]
# Git Status: Everforest Dark Soft BG (#3A454A), Green (#A7C080)
style = "bg:#3A454A fg:#A7C080"
format = '[$all_status$ahead_behind ]($style)'

 

 

 

 

 

 

[python]
# Python: Everforest Dark Hard BG (#2B3339), Blue Accent (#7FBBB3)
style = "bg:#2B3339 fg:#7FBBB3"
format = '[(\($virtualenv\) )]($style)'

 

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
# Time: Everforest Aqua BG (#83C092), Dark Hard FG (#2B3339)
style = "bg:#83C092 fg:#2B3339"
format = '[ $time ]($style)'
