format = """
[ ](#43474E)\
$python$username\
[ ](bg:#8D9199 fg:#43474E)\
$directory\
[ ](fg:#8D9199 bg:#E1E2E9)\
$git_branch$git_status\
[ ](fg:#E1E2E9 bg:#A4C9FE)\
$time\
[ ](fg:#A4C9FE)\
"""
command_timeout = 1200
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#43474E"
style_root = "bg:#43474E"
format = '[$user ]($style)'

[directory]
style = "bg:#8D9199"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "   "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "   "

[git_branch]
symbol = ""
style = "bg:#E1E2E9"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#E1E2E9"
format = '[$all_status$ahead_behind ]($style)'

[python]
style = "bg:#43474E"
format = '[(\($virtualenv\) )]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#A4C9FE"
format = '[ $time ]($style)'
