format = """
[](#42474E)\
$python$username\
[](bg:#8C9199 fg:#42474E)\
$directory\
[](fg:#8C9199 bg:#E1E2E8)\
$git_branch$git_status\
[](fg:#E1E2E8 bg:#9FCAFC)\
$time\
[ ](fg:#9FCAFC)\
"""
command_timeout = 1200
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#42474E"
style_root = "bg:#42474E"
format = '[$user ]($style)'

[directory]
style = "bg:#8C9199"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#E1E2E8"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#E1E2E8"
format = '[$all_status$ahead_behind ]($style)'

[python]
style = "bg:#42474E"
format = '[(\($virtualenv\) )]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#9FCAFC"
format = '[ $time ]($style)'
