format = """
[](#40484C)\
$python$username\
[](bg:#8A9297 fg:#40484C)\
$directory\
[](fg:#8A9297 bg:#DFE3E7)\
$git_branch$git_status\
[](fg:#DFE3E7 bg:#8BD0F0)\
$time\
[ ](fg:#8BD0F0)\
"""
command_timeout = 1200
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#40484C"
style_root = "bg:#40484C"
format = '[$user ]($style)'

[directory]
style = "bg:#8A9297"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#DFE3E7"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#DFE3E7"
format = '[$all_status$ahead_behind ]($style)'

[python]
style = "bg:#40484C"
format = '[(\($virtualenv\) )]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#8BD0F0"
format = '[ $time ]($style)'
