format = """
[](#2E3440)\
 $python$username\
[](bg:#3B4252 fg:#2E3440)\
 $directory\
[](fg:#3B4252 bg:#434C5E)\
 $git_branch$git_status\
[](fg:#434C5E bg:#88C0D0)\
 $time\
[ ](fg:#88C0D0)\
"""
command_timeout = 1200
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
# User: Nord Dark BG (#2E3440), Snow (#D8DEE9)
style_user = "bg:#2E3440 fg:#D8DEE9"
# Root: Nord Orange (#D08770), Dark BG (#2E3440)
style_root = "bg:#D08770 fg:#2E3440"
format = '[ $user ]($style)'

[directory]
# Directory: Nord Medium BG (#3B4252), Snow (#D8DEE9)
style = "bg:#3B4252 fg:#D8DEE9"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "





[git_branch]
symbol = ""
# Git Branch: Nord Light BG (#434C5E), Yellow (#EBCB8B)
style = "bg:#434C5E fg:#EBCB8B"
format = '[ $symbol $branch ]($style)'

[git_status]
# Git Status: Nord Light BG (#434C5E), Green (#A3BE8C)
style = "bg:#434C5E fg:#A3BE8C"
format = '[$all_status$ahead_behind ]($style)'








[python]
# Python: Nord Dark BG (#2E3440), Frost (#8FBCBB)
style = "bg:#2E3440 fg:#8FBCBB"
format = '[(\($virtualenv\) )]($style)'








[time]
disabled = false
time_format = "%R" # Hour:Minute Format
# Time: Nord Cyan BG (#88C0D0), Dark BG (#2E3440)
style = "bg:#88C0D0 fg:#2E3440"
format = '[ $time ]($style)'
